apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bddordergoodfood-develop
  name: bddordergoodfood-develop
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: bddordergoodfood-develop
status:
  loadBalancer: {}
