version: "3.7"

services:
    apiordergoodfood-develop:
        container_name: api-ordergoodfood-develop
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        env_file: .env
        depends_on:
            - bddordergoodfood-develop
            - rabbitmqgoodfood-develop
        ports:
            - 80:80
            - 443:443
        networks:
            - netapiordergoodfood-develop
            - netbddordergoodfood-develop
            - netrabbitmqgoodfood-develop

    rabbitmqgoodfood-develop:
        container_name: rabbitmq-goodfood-develop
        image: rabbitmq:3-management
        restart: always
        env_file: .env
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - netrabbitmqgoodfood-develop

    bddordergoodfood-develop:
        container_name: mysql-ordergoodfood-develop
        image: mysql:8.0
        restart: always
        networks:
            - netbddordergoodfood-develop
        env_file: .env
        volumes:
            - volbddordergoodfood-develop:/var/lib/mysql        

networks:
    netapiordergoodfood-develop:
        name: netapiordergoodfood-develop
    netrabbitmqgoodfood-develop:
        name: netrabbitmqgoodfood-develop
    netbddordergoodfood-develop:
        name: netbddordergoodfood-develop

volumes:
    volbddordergoodfood-develop:
        driver: local
        driver_opts: 
            o: bind
            type: none
            device: ~/bddordergoodfood-data-develop