version: "3.7"

services:
    apiordergoodfood-develop:
        container_name: api-ordergoodfood-develop
        image: ghcr.io/mrpaulin39/goodfood-orders-test:latest
        restart: always
        environment:
            - CONNECTION_STRING=Server=bddordergoodfood-develop;Database=dborders;Uid=root;Pwd=rootpassword;
            - RabbitMQ__Hostname=rabbitmq-goodfood-develop
            - RabbitMQ__Username=admin
            - RabbitMQ__Password=admin
        depends_on:
            - bddordergoodfood-develop
            - rabbitmqgoodfood-develop
        ports:
            - 80:80

    rabbitmqgoodfood-develop:
        container_name: rabbitmq-goodfood-develop
        image: rabbitmq:3.8.25-management-alpine
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - 15672:15672
            - 5672:5672

    bddordergoodfood-develop:
        container_name: mysql-ordergoodfood-develop
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_USER=goodfood
            - MYSQL_PASSWORD=foodgood
        ports:
            - 3306:3306
        volumes:
            - volbddordergoodfood-develop:/var/lib/mysql        

volumes:
    volbddordergoodfood-develop:
        name: "bddOrderGoodFood-Data-Develop"
        driver: local
        driver_opts: 
            o: bind
            type: none
            device: ~/bddordergoodfood-data-develop